server:
  port: 8000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
     enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mustache:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true